- hosts: all
  become: yes
  gather_facts: false

  tasks:
   - name: Add ssh key
     ansible.posix.authorized_key:
       user: vagrant
       state: present
    #   key: "{{ lookup('file', 'public_keys/id_rsa.pub') }}"
       key: "{{ lookup('file', item) }}"
     with_fileglob:
       - "public_keys/*.pub"
