- hosts: all
  become: yes
  gather_facts: false

  tasks:
   - name: Add ssh keys
     ansible.posix.authorized_key:
       user: vagrant
       state: present
       key: "{{ lookup('file', item) }}"
     with_fileglob:
       - "public_keys/*.pub"
