- hosts: all
  become: yes
  gather_facts: false

  tasks:
   - name: Install docker packages
     remote_user: vagrant
     apt:
       name: ['docker']
       state: present
       update_cache: yes
   - name: Ensure group docker exists
     ansible.builtin.group:
       name: docker
       state: present
   - name: Ensure user vagrant has group docker
     ansible.builtin.user:
       name: vagrant
       groups: docker
       append: yes
       state: present
   - name: Install docker-compose packages
     remote_user: vagrant
     apt:
       name: ['docker-compose']
       state: present
       update_cache: yes
   - name: Run Docker Compose
     community.docker.docker_compose:
       project_src: /vagrant
     register: output
